mak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mak.views import home_page
from azbankgateways.urls import az_bank_gateways_urls
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    # path('header', header, name='header'),
    path('', include('product.urls', namespace='products')),
    path('', include('salesman_profile.urls', namespace='salesman_profile')),
    path('', include('customer_profile.urls', namespace='customer_profile')),
    path('', include('comment.urls', namespace='comments')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('payment.urls', namespace='payment')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('cart.urls', namespace='carts')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salesman_profile/urls.py
from django.urls import path
from .views import registersalesman, salesmanlogout, salesman_login, email_activate, forget_password, forget_pass, set_true

app_name = 'salesman_profile'

urlpatterns = [
    path('registersalesman/', registersalesman, name='registersalesman'),
    path('salesmanlogout/', salesmanlogout, name='salesmanlogout'),
    path('salesman_login/', salesman_login, name='salesman_login'),
    path('email_activate/<str:uidb64>/<str:token>', email_activate, name='email_activate'),
    path('forget_password/', forget_password, name='forget_password'),
    path('forget_pass/', forget_pass, name='forget_pass'),
    path("set_true/<str:uidb64>/<str:token>", set_true, name="set_true")    
]

salesman_profile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(email, password, **extra_fields)



class User(AbstractUser):
    username = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    # phone_number = models.CharField(max_length=11)
    date_joined = None


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    class Meta:
        db_table = 'auth_user'


class SalesmanProfile(User):
    telephone = models.CharField(max_length=11, null=True, blank=True)
    phone_number = models.CharField(max_length=11, null=True, blank=True)

    def __str__(self) -> str:
        return self.username


class SalesmanAddress(models.Model):
    address = models.TextField()
    postal_code = models.CharField(max_length=10)
    salesman_id = models.ForeignKey(SalesmanProfile, related_name='salesman_ad', on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return f'{self.salesman_id} {self.address}'



# User.objects.create_user

salesman_profile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.core import validators



User = get_user_model()


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email',
                  'password1', 'password2']
        labels = {
            "email": "ایمیل",
            "password1": "رمز عبور",
            "password2": "تکرار رمز عبور",

        }

        help_texts = {
            "email": "ایمیل خود را به درستی وارد کنید",
        }

    def save(self, commit=True):
        '''
        override user create form to create profile after register!
        '''
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()

        return user


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name')


class RegisterFormSalesman(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا نام کاربری خود را وارد نمایید'}),
        label='نام کاربری',
        validators=[
            validators.MaxLengthValidator(limit_value=20,
                                          message='تعداد کاراکترهای وارد شده نمیتواند بیشتر از 20 باشد'),
            validators.MinLengthValidator(8, 'تعداد کاراکترهای وارد شده نمیتواند کمتر از 8 باشد')
        ]
    )

    email = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید'}),
        label='ایمیل',
        validators=[
            validators.EmailValidator('ایمیل وارد شده معتبر نمیباشد')
        ]
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید'}),
        label='کلمه ی عبور'
    )

    re_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا تکرار کلمه عبور خود را وارد نمایید'}),
        label='تکرار کلمه ی عبور'
    )


    def clean_username(self):
        username = self.cleaned_data.get('username')
        is_exists_user_by_username = User.objects.filter(username=username).exists()

        if is_exists_user_by_username:
            raise forms.ValidationError('این کاربر قبلا ثبت نام کرده است')

        return username

    def clean_re_password(self):
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')
        print(password)
        print(re_password)

        if password != re_password:
            raise forms.ValidationError('کلمه های عبور مغایرت دارند')

        return password

class LoginFormSalesman(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید', 'type':'email', 'class':'form-control'}),
        label='ایمیل'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید', 'type':'password', 'class':'form-control', "id":"password"}),
        label='کلمه ی عبور'
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        is_exists_user = User.objects.filter(email=email).exists()
        if not is_exists_user:
            raise forms.ValidationError('کاربری با مشخصات وارد شده ثبت نام نکرده است')

        return email

# class EmailBoxForm(forms.Form):
#     text = forms.CharField(
#         widget=forms.TextInput(attrs={'placeholder': 'لطفا نام کاربری خود را وارد نمایید', 'type':'text', 'class':'form-control'}),
#         label='کد تایید نهایی'
#     )


class ForgetPasswordForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید', 'type':'email', 'class':'form-control'}),
        label='ایمیل'
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        is_exists_user = User.objects.filter(email=email).exists()
        if not is_exists_user:
            raise forms.ValidationError('کاربری با ایمیل وارد شده ثبت نام نکرده است')

        return email


class ForgetPassForm(forms.Form):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید'}),
        label='کلمه ی عبور'
    )

    re_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا تکرار کلمه عبور خود را وارد نمایید'}),
        label='تکرار کلمه ی عبور'
    )

    def clean_re_password(self):
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')
        if password != re_password:
            raise forms.ValidationError('کلمه های عبور مغایرت دارند')

        return password

    # def save(self, commit: bool = ...) :
    #     self.instance.set_password(self.cleaned_data.get("password"))
    #     return super().save(commit=commit)

salesman_profile/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from markupsafe import re
from salesman_profile.models import SalesmanProfile
from .forms import RegisterFormSalesman, ForgetPassForm, ForgetPasswordForm
from django.contrib.auth import login, authenticate, logout
import uuid
from django.core.mail import send_mail
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from verification_email_token_gen import account_activation_token
from django.core.cache import cache
from django.conf import settings
from uuid import uuid4
from django.urls import reverse
from .models import User
from django.core import validators
from django import forms




def final_verification(subject, message, email_from, recipient_list):
    send_mail( subject, message, email_from, recipient_list)

def registersalesman(request):
    register_form = RegisterFormSalesman(request.POST or None)

    if register_form.is_valid():
        email = register_form.cleaned_data['email']
        username = register_form.cleaned_data.get('username')
        password = register_form.cleaned_data.get('password')
        user = SalesmanProfile.objects.create_user(username=username, email=email, password=password, is_active=False, is_staff=False)
        cache.set('user',user, 200)
        current_site = get_current_site(request)
        uid = str(uuid.uuid1())
        cache.set('uid', uid, 120)
        subject = 'thank your for registering to mak store'
        message = render_to_string('salesman_profile/activate_mail.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
        })
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [ email,]
        final_verification(subject, message, email_from, recipient_list)
        request.session['form'] = request.POST
        return redirect('/')
    return render(request, 'salesman_profile/salesmanregister.html', {'register_form': register_form})


# def email_activate(request):
#     register_form = RegisterFormSalesman(request.session['post'])
#     if request.method == 'GET':
#         return render(request, 'salesman_profile/emailshowbox.html', {})
#     elif request.method == 'POST':
#         if register_form.is_valid():
#             uid = request.POST.get('uid')
#             cache.set(uid, 120)
#             register_form.save(commit=True)
#             return redirect('/')

def email_activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = SalesmanProfile.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, SalesmanProfile.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.is_staff = True
        user.save()
        return render(request, 'salesman_profile/emailshowbox.html')
    else:
        return HttpResponse('Activation link is invalid!')



def salesmanlogout(request):
    logout(request)
    return redirect('/login')

# def salesman_login(request):
#     if request.user.is_authenticated:
#         return redirect('/')
    
#     login_form = LoginFormSalesman(request.POST or None)
#     if request.method == "GET":
#         context = {
#             'login_form': login_form
#         }
#         return render(request, 'salesman_profile/salesmanlogin.html', context)
#     elif request.method == "POST":
#         if login_form.is_valid():
#             email = login_form.cleaned_data.get('email')
#             password = login_form.cleaned_data.get('password')
#             user = authenticate(request, email=email, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('/')
#             else:
#                 login_form.add_error('email', 'کاربری با مشخصات وارد شده یافت نشد')

#             return redirect('/')    


def salesman_login(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == "GET":
        return render(request, 'salesman_profile/loginsalesman.html', {})
    else:
        email = request.POST.get('email', "")
        password = request.POST.get("password", "")
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
        return redirect('/')


def forget_password(request):
    forget_password_form = ForgetPasswordForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'salesman_profile/forget_password.html', {'forget_password_form': forget_password_form})

    elif request.method == "POST":
        if forget_password_form.is_valid():
            email = forget_password_form.cleaned_data.get("email")
            cache.set('email_miss',email,300)
            user = SalesmanProfile.objects.get(email=email)
            if user:
                uid = str(uuid.uuid1())
                cache.set('uid', uid, 120)
                current_site = get_current_site(request)
                subject = 'thank your for registering to mak store'
                message = render_to_string('salesman_profile/set_tru.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': account_activation_token.make_token(user),
                })
                email_from = settings.EMAIL_HOST_USER

                recipient_list = [ email,]
                final_verification(subject, message, email_from, recipient_list)

                return redirect('/') # badan behesh ye message bede
            else:
                raise forms.ValidationError('همچین کاربری یافت نشد')


def set_true(request,uidb64 ,token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = SalesmanProfile.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, SalesmanProfile.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        return redirect('salesman_profile:forget_pass')
    else:
        return HttpResponse('Activation link is invalid!')


def forget_pass(request):
    forget_pass_form = ForgetPassForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'salesman_profile/forget_pass.html', {'forget_pass_form': forget_pass_form})
    elif request.method == "POST":
        print('in chache',cache.get('email_miss'))
        user = SalesmanProfile.objects.get(email=cache.get('email_miss'))
        if forget_pass_form.is_valid():
            password = request.POST.get("password", "")
            user.set_password(password)
            user.save()
            login(request,user)
            return redirect("home")
        else:
            return redirect("salesman_profile:forget_password")

salesman_profile/templates/salesman_profile/activate_mail.html
{% autoescape off %}
    سلام {{ user.email }}
    {% comment %} {{uid}}
    {{token}} {% endcomment %}

    http://{{ domain }}{% url 'salesman_profile:email_activate' uidb64=uid token=token %}
{% endautoescape %}

salesman_profile/templates/salesman_profile/emailshowbox.html
{% extends 'base.html' %}

{% block content %}
<section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
    <div class="area-breadcrumb-site">
        <h1 class="text-center mb-3">ورود</h1>
        <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
            <ol class="breadcrumb breadcrumb-singleProduct ">
                <li class="breadcrumb-item"><a href="#">خانه</a></li>
                <li class="breadcrumb-item active">ورود</li>
            </ol>
        </nav>
    </div>
</section>

<main class="content">
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-9 col-lg-8  col-xl-6">
                    <div class="login login-register-wrap">
                        <div class="area-form-login area-form-login-register p-3 p-sm-4 p-md-5 ">
                            <h3 class="heading-style1 mb-3">ورود</h3>
                           <h1> sucssesful</h1>
                        </div>
                        <div class="footer-login">
                            <div class="area-socialIcon socialIcon-bg-secondary d-flex justify-content-center">
                                <a href="http://www.facebook.com" class="icon facebook"><span class="tooltip-site">Facebook</span></a>
                                <a href="http://www.github.com" class="icon instegram"><span class="tooltip-site">instegram</span></a>
                                <a href="http://www.dribble.com" class="icon linkedin"><span class="tooltip-site">linkedin</span></a>
                                <a href="http://www.twitter.com" class="icon twitter"><span class="tooltip-site">Twitter</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

salesman_profile/templates/salesman_profile/loginsalesman.html
{% extends 'base.html' %}

{% block content %}
<section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
    <div class="area-breadcrumb-site">
        <h1 class="text-center mb-3">ورود</h1>
        <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
            <ol class="breadcrumb breadcrumb-singleProduct ">
                <li class="breadcrumb-item"><a href="#">خانه</a></li>
                <li class="breadcrumb-item active">ورود</li>
            </ol>
        </nav>
    </div>
</section>

<main class="content">
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-9 col-lg-8  col-xl-6">
                    <div class="login login-register-wrap">
                        <div class="area-form-login area-form-login-register p-3 p-sm-4 p-md-5 ">
                            <h3 class="heading-style1 mb-3">ورود</h3>
                            <form method="post" action="{% url 'salesman_profile:salesman_login' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>ایمیل <span class="text-danger ">*</span></label>
                                    <input type="email" required="" placeholder="ایمیل را وارد کنید" class="form-control" name="email">
                                </div>
                                <div class="form-group mb-3">
                                    <label for="Password">پسورد <span class="text-danger ">*</span></label>
                                    <input type="password" required="" name="password" id="password" class="form-control input-password" placholder="رمز عبور را وارد کنید" aria-label="Enter Password" aria-describedby="basic-addon2" name="password">
                                    <span class="icon-eye-password" id="basic-addon2">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class=" d-sm-flex justify-content-between">
                                    <div class="form-check form-check-custom ">
                                        <label class="checkbox-container"> مرا به خاطر بسپار
                                            <input type="checkbox" checked="">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="forget_password"> <a href="{% url 'salesman_profile:forget_password' %}">
                                            رمز عبور را فراموش کرده اید؟</a>
                                    </div>
                                </div> <button class="btn-animate1 mt-4">ورود</button>
                        
                                <div class="form-note mt-4">حساب کاربری ندارید؟ <a href="signup.html">ثبت نام
                                        کنید</a></div>
                            </form>
                        </div>
                        <div class="footer-login">
                            <div class="area-socialIcon socialIcon-bg-secondary d-flex justify-content-center">
                                <a href="http://www.facebook.com" class="icon facebook"><span class="tooltip-site">Facebook</span></a>
                                <a href="http://www.github.com" class="icon instegram"><span class="tooltip-site">instegram</span></a>
                                <a href="http://www.dribble.com" class="icon linkedin"><span class="tooltip-site">linkedin</span></a>
                                <a href="http://www.twitter.com" class="icon twitter"><span class="tooltip-site">Twitter</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

salesman_profile/templates/salesman_profile/salesmanlogin.html
{% extends 'base.html' %}

{% block content %}
<section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
    <div class="area-breadcrumb-site">
        <h1 class="text-center mb-3">ورود</h1>
        <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
            <ol class="breadcrumb breadcrumb-singleProduct ">
                <li class="breadcrumb-item"><a href="#">خانه</a></li>
                <li class="breadcrumb-item active">ورود</li>
            </ol>
        </nav>
    </div>
</section>

<main class="content">
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-9 col-lg-8  col-xl-6">
                    <div class="login login-register-wrap">
                        <div class="area-form-login area-form-login-register p-3 p-sm-4 p-md-5 ">
                            <h3 class="heading-style1 mb-3">ورود</h3>
                            <form method="post" action="{% url 'salesman_profile:salesman_login' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="{{ login_form.email.id_for_label }}">ایمیل <span class="text-danger ">*</span></label>
                                    {{ login_form.email }}
                                    {% for error in login_form.email.errors %}
                                        <p style="color: red;">{{ error }}</p>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="{{ login_form.password.id_for_label }}">پسورد <span class="text-danger ">*</span></label>
                                    {{ login_form.password }}
                                    {% for error in login_form.password.errors %}
                                        <p style="color: red;">{{ error }}</p>
                                    {% endfor %}
                                    <span class="icon-eye-password" id="basic-addon2">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class=" d-sm-flex justify-content-between">
                                    <div class="form-check form-check-custom ">
                                        <label class="checkbox-container"> مرا به خاطر بسپار
                                            <input type="checkbox" checked="">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="forget_password"> <a href="#">
                                            رمز عبور را فراموش کرده اید؟</a>
                                    </div>
                                </div> <button class="btn-animate1 mt-4">ورود</button>

                                <div class="form-note mt-4">حساب کاربری ندارید؟ <a href="signup.html">ثبت نام
                                        کنید</a></div>
                            </form>
                        </div>
                        <div class="footer-login">
                            <div class="area-socialIcon socialIcon-bg-secondary d-flex justify-content-center">
                                <a href="http://www.facebook.com" class="icon facebook"><span class="tooltip-site">Facebook</span></a>
                                <a href="http://www.github.com" class="icon instegram"><span class="tooltip-site">instegram</span></a>
                                <a href="http://www.dribble.com" class="icon linkedin"><span class="tooltip-site">linkedin</span></a>
                                <a href="http://www.twitter.com" class="icon twitter"><span class="tooltip-site">Twitter</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

salesman_profile/templates/salesman_profile/salesmanregister.html
{% extends 'base.html' %}

{% block content %}

<section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
    <div class="area-breadcrumb-site">
        <h1 class="text-center mb-3">ثبت نام</h1>
        <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
            <ol class="breadcrumb breadcrumb-singleProduct ">
                <li class="breadcrumb-item"><a href="#">خانه</a></li>
                <li class="breadcrumb-item active">ثبت نام</li>
            </ol>
        </nav>
    </div>
</section>


<main class="content">
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-9 col-lg-8  col-xl-6">
                    <div class="register login-register-wrap">
                        <div class="area-form-register area-form-login-register  p-3 p-sm-4 p-md-5 ">
                            <h3 class="heading-style1 mb-3">ثبت نام</h3>
                            <form method="post" action="{% url 'salesman_profile:registersalesman' %}">
                                {% csrf_token %}
                                {{ register_form }}

                                <button class="btn-animate1 mt-4">ثبت نام</button>
                                <div class="form-note mt-4">حساب کاربری دارید؟ <a href="login.html">وارد شوید</a>
                                </div>
                            </form>
                        </div>
                        <div class="footer-login">
                            <div class="area-socialIcon socialIcon-bg-secondary d-flex justify-content-center">
                                <a href="http://www.facebook.com" class="icon facebook"><span class="tooltip-site">Facebook</span></a>
                                <a href="http://www.github.com" class="icon instegram"><span class="tooltip-site">instegram</span></a>
                                <a href="http://www.dribble.com" class="icon linkedin"><span class="tooltip-site">linkedin</span></a>
                                <a href="http://www.twitter.com" class="icon twitter"><span class="tooltip-site">Twitter</span></a> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

salesman_profile/templates/salesman_profile/set_tru.html
{% autoescape off %}
    سلام {{ user.email }}
    {% comment %} {{uid}}
    {{token}} {% endcomment %}

    http://{{ domain }}{% url 'salesman_profile:set_true' uidb64=uid token=token %}
{% endautoescape %}

salesman_profile/templates/salesman_profile/vertification_mail.html
{% autoescape off %}
    سلام {{ user.email }}
    {% comment %} {{uid}}
    {{token}} {% endcomment %}

    http://{{ domain }}{% url 'salesman_profile:set_true' uidb64=uid token=token %}
{% endautoescape %}