customer_profile/urls.py
import imp
from django.urls import path, include
from .views import (registercustomer, customer_login, customerlogout, email_activate,
                        forget_password, forget_pass, set_true, checkForActivationMail, 
                            profilecustomer, my_address, my_comments)

from customer_profile.my_api.views import MyUserLoginTokenPairView, RegisterView, ProfileList, ProfileDetail, ProfileUpdate
from rest_framework_simplejwt.views import TokenRefreshView
from rest_framework.routers import DefaultRouter

app_name = 'customer_profile'

profile_update = ProfileList.as_view({
    'get': 'retrieve',
    'put': 'update'
})

router = DefaultRouter(trailing_slash=False)
router.register(r'customerapi', ProfileList)


urlpatterns = [
    path('registercustomer/', registercustomer, name='registercustomer'),
    path('customerlogout/', customerlogout, name='customerlogout'),
    path('customer_login/', customer_login, name='customer_login'),
    path('email_activate_customer/<str:uidb64>/<str:token>', email_activate, name='email_activate_customer'),
    path('checkForActivationMail/', checkForActivationMail, name='checkForActivationMail'),
    path('forget_password_customer/', forget_password, name='forget_password_customer'),
    path('forget_pass_customer/', forget_pass, name='forget_pass_customer'),
    path("set_true_customer/<str:uidb64>/<str:token>", set_true, name="set_true"),
    path("profilecustomer/", profilecustomer, name="profilecustomer"),
    path("my_address/", my_address, name="my_address"),
    path("my_comments/", my_comments, name="my_comments"),
    path('login-api/', MyUserLoginTokenPairView.as_view(), name='token_obtain_pair'),
    path('login-api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register-api/', RegisterView.as_view(), name='auth_register'),
    path('profile-api/<int:pk>/', profile_update, name='profile_api'),
    path('myprofile-api/<int:pk>/', ProfileDetail.as_view(), name='myprofile_api'),
    path('myprofile-api-up/<int:pk>/', ProfileUpdate.as_view(), name='ProfileUpdate')
]

urlpatterns += router.urls

mak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mak.views import home_page
from azbankgateways.urls import az_bank_gateways_urls
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    # path('header', header, name='header'),
    path('', include('product.urls', namespace='products')),
    path('', include('salesman_profile.urls', namespace='salesman_profile')),
    path('', include('customer_profile.urls', namespace='customer_profile')),
    path('', include('comment.urls', namespace='comments')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('payment.urls', namespace='payment')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('cart.urls', namespace='carts')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_profile/models.py
from django.db import models
# from django.contrib.auth.models import User
from product.models import Product
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomerProfile(User):
    telephone = models.CharField(max_length=11, null=True, blank=True)
    phone_number = models.CharField(max_length=11, null=True, blank=True)

    def __str__(self) -> str:
        return self.username



class CustomerAddress(models.Model):
    address = models.TextField()
    postal_code = models.CharField(max_length=10)
    customer = models.ForeignKey(CustomerProfile, related_name='customer_ad', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.customer} {self.address}'



class Favotite(models.Model):
    user = models.ForeignKey(CustomerProfile, related_name='users', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='product_fav', on_delete=models.DO_NOTHING) # badan dar view handle shavad

customer_profile/my_api/views.py
# django

from customer_profile.models import CustomerAddress, CustomerProfile
import redis
from django.shortcuts import get_object_or_404

# django rest
from rest_framework import mixins
from rest_framework import viewsets
from .serializers import MyTokenObtainPairSerializer
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView
from .serializers import RegisterSerializer, ProfileSerializer, ProfileAddressSerializer
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status



class MyUserLoginTokenPairView(TokenObtainPairView):
    permission_classes = (AllowAny,)
    serializer_class = MyTokenObtainPairSerializer



class RegisterView(generics.CreateAPIView):
    queryset = CustomerProfile.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer



class ProfileList(viewsets.ModelViewSet):
    queryset = CustomerProfile.objects.all()
    serializer_class = ProfileSerializer


class ProfileDetail(mixins.CreateModelMixin, mixins.RetrieveModelMixin, generics.GenericAPIView):
    queryset = CustomerAddress.objects.all()
    serializer_class = ProfileAddressSerializer
    lookup_field = 'pk'

    def get(self, request, pk, format=None):
        queryset = CustomerAddress.objects.all()
        user = get_object_or_404(queryset, pk=pk)
        serializer = ProfileAddressSerializer(user)
        return Response(serializer.data)

    def post(self, request, pk, format=None):
        serializer = ProfileAddressSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,  status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProfileUpdate(generics.UpdateAPIView):
    queryset = CustomerAddress.objects.all()
    serializer_class = ProfileAddressSerializer

customer_profile/views.py
from itertools import product
from django.template.loader import render_to_string
from markupsafe import re
from customer_profile.models import CustomerProfile, CustomerAddress
from product.models import Product
from .forms import RegisterFormCustomer, LoginFormCustomer,  ForgetPassForm, ForgetPasswordForm, ProfileDetail
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
import uuid
from django.core.mail import send_mail
from django.core.cache import cache
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from verification_email_token_gen import account_activation_token
from .models import User
from django.core import validators
from django import forms
from django.contrib.auth.decorators import login_required
from comment.models import Comment
import redis
from .tasks import send_email_task


def final_verification(subject, message, email_from, recipient_list):
    # send_mail( subject, message, email_from, recipient_list)
    send_email_task(subject, message, email_from, recipient_list)



def registercustomer(request):
    register_form = RegisterFormCustomer(request.POST or None)

    if register_form.is_valid():
        email = register_form.cleaned_data['email']
        username = register_form.cleaned_data.get('username')
        password = register_form.cleaned_data.get('password')

        user = CustomerProfile.objects.create_user(username=username, email=email, password=password, is_active=False)
        cache.set('user',user, 200)
        current_site = get_current_site(request)

        uid = str(uuid.uuid1())
        cache.set('uid', uid, 120)
        subject = 'thank your for registering to mak store'
        message = render_to_string('customer_profile/vertification_mail.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
        })
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [ email,]
        final_verification(subject, message, email_from, recipient_list)
        request.session['form'] = request.POST
        return redirect('customer_profile:checkForActivationMail')
    return render(request, 'customer_profile/customer_register.html', {'register_form': register_form})


def checkForActivationMail(request):
    return render(request, 'customer_profile/email_okbox.html')




def email_activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = CustomerProfile.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomerProfile.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'customer_profile/emailshowbox.html')
    else:
        return HttpResponse('Activation link is invalid!')


def customerlogout(request):
    logout(request)
    return redirect('customer_profile:customer_login')



def customer_login(request):
    if request.user.is_authenticated:
        return redirect('/')
    
    login_form = LoginFormCustomer(request.POST or None)
    
    if request.method == "GET":
        context = {
            'login_form': login_form
        }
        return render(request, 'customer_profile/customer_login.html', context)
    elif request.method == "POST":
        if login_form.is_valid():
            email = login_form.cleaned_data.get('email')
            password = login_form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                r=redis.Redis()
                try:
                    key=request.session.session_key
                    cart=r.hgetall(key)
                    r.hset(email,mapping=cart)
                except:
                    pass
                login(request, user)
                return redirect('/')
            else:
                login_form.add_error('email', 'کاربری با مشخصات وارد شده یافت نشد')

            return redirect('/')

        else:#if user already not register
            print(f"error:{login_form.errors}")
            return redirect('customer_profile:registercustomer')


def forget_password(request):
    forget_password_form = ForgetPasswordForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'customer_profile/forget_password.html', {'forget_password_form': forget_password_form})

    elif request.method == "POST":
        if forget_password_form.is_valid():
            email = forget_password_form.cleaned_data.get("email")
            cache.set('email_miss',email,300)
            user = CustomerProfile.objects.get(email=email)
            if user:
                uid = str(uuid.uuid1())
                cache.set('uid', uid, 120)
                current_site = get_current_site(request)
                subject = 'thank your for registering to mak store'
                message = render_to_string('customer_profile/set_tru.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': account_activation_token.make_token(user),
                })
                email_from = settings.EMAIL_HOST_USER

                recipient_list = [ email,]
                final_verification(subject, message, email_from, recipient_list)

                return redirect('/') # badan behesh ye message bede
            else:
                raise forms.ValidationError('همچین کاربری یافت نشد')


def set_true(request,uidb64 ,token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = CustomerProfile.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomerProfile.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        return redirect('customer_profile:forget_pass_customer')
    else:
        return HttpResponse('Activation link is invalid!')


def forget_pass(request):
    forget_pass_form = ForgetPassForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'customer_profile/forget_pass.html', {'forget_pass_form': forget_pass_form})
    elif request.method == "POST":
        user = CustomerProfile.objects.get(email=cache.get('email_miss'))
        if forget_pass_form.is_valid():
            password = request.POST.get("password", "")
            user.set_password(password)
            user.save()
            login(request,user)
            return redirect("home")
        else:
            return redirect("customer_profile:forget_password_customer")

# login required
def profilecustomer(request):
    user_id = request.user.id
    user_all = CustomerProfile.objects.all().values_list('id', flat=True)
    l_user = []
    for elm in user_all:
        l_user.append(elm)
    if user_id in l_user:
        user = CustomerProfile.objects.get(id=user_id)
        form = ProfileDetail(request.POST or None)
        if request.method == "POST":
            if form.is_valid():
                # name = form.cleaned_data.get("name")
                # familyname = form.cleaned_data.get("familyname")
                # email = form.cleaned_data.get("email")
                telephone = form.cleaned_data.get("telephone")
                phone_number = form.cleaned_data.get("phone_number")
                address = form.cleaned_data.get("address")
                postal_code = form.cleaned_data.get("postal_code")

                CustomerProfile.objects.update(telephone=telephone, phone_number=phone_number)
                a = CustomerAddress()
                a.address = address
                a.postal_code = postal_code
                a.customer = user
                a.save()
                return redirect('customer_profile:profilecustomer')

        return render(request, 'customer_profile/account-details.html', {"form" : form})
    else:
        return redirect("home")


def my_address(request):
    user_id = request.user.id
    user_all = CustomerProfile.objects.all().values_list('id', flat=True)
    l_user = []
    print(Comment.objects.filter(customer__id=user_id).values('product__id'))
    for elm in user_all:
        l_user.append(elm)
    if user_id in l_user:
        customer_profile = CustomerProfile.objects.filter(id=user_id).values_list('phone_number', flat=True)
        my_phone = list(customer_profile)
        customer_address = CustomerAddress.objects.filter(customer__id=user_id)
        return render(request, 'customer_profile/account-address.html', {'customer_number': my_phone[0], 'customer_addresss':customer_address})
    else:
        return redirect("home")


def my_comments(request):
    user_id = request.user.id
    user_all = CustomerProfile.objects.all().values_list('id', flat=True)
    l_user = []
    for elm in user_all:
        l_user.append(elm)
    if user_id in l_user:
        my_comment = Comment.objects.filter(customer__id=user_id)
        if request.method == "GET":
            context = {
                'my_comments' : my_comment,
            }
            return render(request, 'customer_profile/account-comments.html', context)
        elif request.method == "POST":
            cm_del = request.POST.get('cm_delete')
            delete_cm = Comment.objects.filter(id=cm_del)
            delete_cm.delete()
            return redirect("customer_profile:my_comments")
    else:
        return redirect("home")

customer_profile/templates/customer_profile/account-address.html
{% extends 'customer_profile/base-account.html' %}
{% load static %}


{% block account_content %}


<div class="account-content content-address-account">


    <div class="header-tab-content-account  mb-4">
        <h1 class="title-tabcontent-account">
            نشانی ها
        </h1>
    </div>
    <div class="main-content-account">
        <div class="profile-address-container">
            {% comment %} <div class="profile-address-itemTop mb-3"> اهواز_ کوی مجاهد، کوچه هنر 4 پلاک 15
            </div> {% endcomment %}
            <div class="profile-address-content">
                <ul>
                    {% for address in customer_addresss %}
                        <li>
                            <div class="profile-address-item profile-address-item-location mb-2">
                                <i class="fal fa-map-marker-alt me-2"> {{ address.address }}</i></div>
                        </li>
                    {% endfor %}
                    <li>
                        <div class="profile-address-item profile-address-item-postalCode mb-2">
                            <i class="far fa-envelope me-2"></i>{{ request.user.email }}</div>
                    </li>
                    
                    <li>
                        <div class="profile-address-item profile-address-item-phone mb-2"><i class="fal fa-phone-alt me-2"></i>{{ customer_number }}</div>
                    </li>
                    
                    <li>
                        <div class="profile-address-item profile-address-item-name mb-2"><i class="fal fa-user me-2"></i>{{ request.user.username }}</div>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>



</div>

{% endblock %}

customer_profile/templates/customer_profile/account-details.html
{% extends 'customer_profile/base-account.html' %}
{% load static %}


{% block account_content %}
<div class="account-content content-details-account">
    <div class="header-tab-content-account d-flex justify-content-between align-items-center mb-4">
        <h1 class="title-tabcontent-account">
            اطلاعات حساب
        </h1>
    </div>
    <div class="main-content-account">
        <div class="area-form-wrap">
            <form method="post" action="{% url 'customer_profile:profilecustomer' %}">
                <div class="row">
                    {% csrf_token %}
                    {{form}}
                    {% comment %} <div class="form-group col-md-6 mb-4">
                        <label for="inputname">نام</label>
                        <input type="text" class="form-control" id="inputname" placeholder="فاطمه">
                    </div>

                    <div class="form-group col-md-6 mb-4">
                        <label for="inputname">نام خانوادگی</label>
                        <input type="text" class="form-control" id="inputname" placeholder="عوفی">
                    </div>
                    <div class="form-group col-md-6 mb-4">
                        <label for="inputbirth">تاریخ تولد</label>
                        <input type="date" class="form-control" id="inputbirth" placeholder="1368/7/2">
                    </div>

                    <div class="custom_select col-md-6 mb-4">
                        <label for="inputState">جنسیت</label>

                        <select class="form-control" id="inputState">
                            <option selected="">مرد</option>
                            <option>زن</option>
                        </select>
                    </div>
                    <div class="form-group col-md-6 mb-4">
                        <label for="inputEmail4">آدرس ایمیل</label>
                        <input type="email" class="form-control" id="inputEmail4" placeholder="example@yahoo.com">
                    </div>
                    <div class="form-group col-md-6 mb-4">
                        <label for="inpustate">استان</label>
                        <input type="text" class="form-control" id="inpustate" placeholder="خوزستان">
                    </div>

                    <div class="form-group col-md-6 mb-4">
                        <label for="inputsity">شهر</label>
                        <input type="text" class="form-control" id="inputsity" placeholder="اهواز">
                    </div>

                    <div class="form-group col-md-6 mb-4">
                        <label for="inputurl">آدرس</label>
                        <input type="text" class="form-control" id="inputurl" placeholder="اهواز-کیان پارس">
                    </div>
                    <div class="form-group col-md-6 mb-4">
                        <label for="inputcodepost">کد پستی</label>
                        <input type="text" class="form-control" id="inputcodepost" placeholder="2541236541">
                    </div>
                    <div class="form-group col-md-6 mb-4">
                        <label for="inputcodemely">کدملی</label>
                        <input type="text" class="form-control" id="inputcodemely" placeholder="1740265123">
                    </div> {% endcomment %}
                </div>
                <div class="text-center mt-3">
                    <button class="btn-animate1 mt-4">بفرست</button>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

customer_profile/templates/customer_profile/account_header.html
{% load static %}

{% block account_header %}

<div class="account-header d-flex justify-content-between justify-content-xl-end">
    <div class="icon_meni_bar d-block d-xl-none">
        <a><img src="{% static 'img/menu.png' %}"></a>
    </div>
    <a class="link-back-home" href="{% url 'home' %}">صفحه نخست <i class="far fa-home"></i></a>
</div>

{% endblock account_header %}

customer_profile/templates/customer_profile/account_sidebar.html
{% load static %}

{% block account_sidebar %}
<div class="col-12 col-lg-3 container-sidebar-account ">
    <div class="sidebar-account">
        <div class="avatar-user d-flex flex-column justify-content-center align-items-center mb-5">
            <img class="img-avatar-user" src="{% static 'img/imgprofile.jpg' %}">
            <div class="name-avatar-user">
                <h4>{{ request.user.username }}</h4>
            </div>
        </div>
        <div class="account-menu ">
            <div class="list-group  flex-column">
                <a class="list-group-item " href="account.html" id="orders-tab"><i class="fal fa-cart-arrow-down me-3"></i>سفارش ها

                </a>
                <a class="list-group-item" href="account-favorits.html" id="favorits-tab">
                    <i class="fal fa-heart me-3"></i>علاقه مندی ها
                </a>
                <a class="list-group-item" href="{% url 'customer_profile:my_comments' %}" id="comment-tab"><i class="fal fa-comment-alt me-3"></i>دیدگاهها
                </a>

                <a class="list-group-item" href="{% url 'customer_profile:my_address' %}" id="contact-tab"><i class="fal fa-map-marker-alt me-3"></i>آدرس ها

                </a>
                <a class="list-group-item" href="{% url 'customer_profile:profilecustomer' %}" id="infoprofile-tab">
                    <i class="fal fa-clipboard-list-check me-3"></i>جزییات حساب
                </a>

                <a class="list-group-item" href="{% url 'customer_profile:forget_password_customer' %}" id="home">
                    <i class="fal fa-lock-alt me-3"></i>تغییر
                    رمز عبور
                </a>
                <a class="list-group-item" href="#"><i class="fal fa-sign-out-alt  me-3"></i>خروج
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock account_sidebar %}

customer_profile/templates/customer_profile/base-account.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>servin-ecommerce bootstrap 5 html template</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
        <!--refrence carousel-->
        <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
        <!--refrence carousel-->
        <link rel="stylesheet" href= "{%static 'css/style.css' %}">
        <link rel="stylesheet" href="{%static 'css/all.min.css'%}">
        <link rel="stylesheet" href="{%static 'css/respansive.css'%}">
        <link rel="stylesheet" href="{%static 'css/animate.min.css'%}">
    </head>

    
<body>
    <main class="content">
        <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
            <div class="container container-Page-account">
                <div class="row">
                    {% block account_sidebar %}
                        {% include 'customer_profile/account_sidebar.html' %}
                    {% endblock account_sidebar %}
                    <div class="col-12 col-xl-9 container-content-account">
                        {% block account_header %}
                            {% include 'customer_profile/account_header.html' %}
                        {% endblock account_header %}
                        {% block account_content %}{% endblock account_content %}
                    </div>
                </div>
            </div>
        </section>
    </main>


    <a class="scrollTo scroll-To-top" href=".topbar-site"></a>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--refrence carousel-->
    <script src="{% static 'js/carousel/owl.carousel.min.js' %}"></script>
    <!--refrence carousel-->
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
</body>
</html>

customer_profile/templates/customer_profile/customer_login.html
{% extends 'base.html' %}

{% block content %}
<section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
    <div class="area-breadcrumb-site">
        <h1 class="text-center mb-3">ورود</h1>
        <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
            <ol class="breadcrumb breadcrumb-singleProduct ">
                <li class="breadcrumb-item"><a href="#">خانه</a></li>
                <li class="breadcrumb-item active">ورود</li>
            </ol>
        </nav>
    </div>
</section>

<main class="content">
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-9 col-lg-8  col-xl-6">
                    <div class="login login-register-wrap">
                        <div class="area-form-login area-form-login-register p-3 p-sm-4 p-md-5 ">
                            <h3 class="heading-style1 mb-3">ورود</h3>
                            <form method="post" action="{% url 'customer_profile:customer_login' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="{{ login_form.email.id_for_label }}">ایمیل <span class="text-danger ">*</span></label>
                                    {{ login_form.email }}
                                    {% for error in login_form.email.errors %}
                                        <p style="color: red;">{{ error }}</p>
                                    {% endfor %}
                                </div>
                                <div class="form-group mb-3">
                                    <label for="{{ login_form.password.id_for_label }}">پسورد <span class="text-danger ">*</span></label>
                                    {{ login_form.password }}
                                    {% for error in login_form.password.errors %}
                                        <p style="color: red;">{{ error }}</p>
                                    {% endfor %}
                                    <span class="icon-eye-password" id="basic-addon2">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class=" d-sm-flex justify-content-between">
                                    <div class="form-check form-check-custom ">
                                        <label class="checkbox-container"> مرا به خاطر بسپار
                                            <input type="checkbox" checked="">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="forget_password"> <a href="{% url 'customer_profile:forget_password_customer' %}">
                                            رمز عبور را فراموش کرده اید؟</a>
                                    </div>
                                </div> <button class="btn-animate1 mt-4">ورود</button>

                                <div class="form-note mt-4">حساب کاربری ندارید؟ <a href="signup.html">ثبت نام
                                        کنید</a></div>
                            </form>
                        </div>
                        <div class="footer-login">
                            <div class="area-socialIcon socialIcon-bg-secondary d-flex justify-content-center">
                                <a href="http://www.facebook.com" class="icon facebook"><span class="tooltip-site">Facebook</span></a>
                                <a href="http://www.github.com" class="icon instegram"><span class="tooltip-site">instegram</span></a>
                                <a href="http://www.dribble.com" class="icon linkedin"><span class="tooltip-site">linkedin</span></a>
                                <a href="http://www.twitter.com" class="icon twitter"><span class="tooltip-site">Twitter</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

customer_profile/templates/customer_profile/set_tru.html
{% autoescape off %}
    سلام {{ user.email }}
    {% comment %} {{uid}}
    {{token}} {% endcomment %}

    http://{{ domain }}{% url 'customer_profile:set_true' uidb64=uid token=token %}
{% endautoescape %}

customer_profile/templates/customer_profile/vertification_mail.html
{% autoescape off %}
    سلام {{ user.email }}
    {{uid}}
    {{token}}

    http://{{ domain }}{% url 'customer_profile:email_activate_customer' uidb64=uid token=token %}
{% endautoescape %}