mak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mak.views import home_page
from azbankgateways.urls import az_bank_gateways_urls
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    # path('header', header, name='header'),
    path('', include('product.urls', namespace='products')),
    path('', include('salesman_profile.urls', namespace='salesman_profile')),
    path('', include('customer_profile.urls', namespace='customer_profile')),
    path('', include('comment.urls', namespace='comments')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('payment.urls', namespace='payment')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('', include('cart.urls', namespace='carts')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
# from .views import show_sub_cat, show_sub_cat_det, ShowProductBySubCategory, ShowProductCategory, ProductList, FilteringAll
from product.views import show_sub_cat, show_sub_cat_det,Detail_Product
from .views import show_sub_cat, show_sub_cat_det, ProductList, FilteringAll
from product.views import show_sub_cat, show_sub_cat_det ,Detail_Product
from .views import show_sub_cat, show_sub_cat_det, ProductList, FilteringAll
from product.views import show_sub_cat, show_sub_cat_det,Detail_Product,add_to_cart

app_name = 'product'

urlpatterns = [
    path('detailproduct/<str:slug>',Detail_Product.as_view(),name="detail_product"),
    path('add_to_cart/<str:slug>',add_to_cart,name='add_to_cart'),
    path('sub_cat/', show_sub_cat, name='sub_cat'),
    path('sub_cat_det/<str:cat>', show_sub_cat_det, name='sub_cat_det'),
    # path('show_product_sub_cat/<str:sub_cat>', ShowProductBySubCategory.as_view(), name='show_product_sub_cat'),
    # path('show_product_cat/<int:id>', ShowProductCategory.as_view(), name='show_product_cat'),
    path('show_product/<str:category>', ProductList.as_view(), name='show_product'),
    path('side_bar_filtering', FilteringAll.as_view(), name='side_bar_filtering'),
]

product/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from salesman_profile.models import SalesmanProfile
from django.utils.text import slugify
# from cart.models import Order

# from customer_profile.models import HistoryCustomer



class CategoryProduct(models.Model):
    title = models.CharField(max_length=255)
    parent = models.ForeignKey('self', related_name='child_cat', on_delete=SET_NULL, null=True, blank=True)
    img = models.ImageField(upload_to='static/img', null=True, blank=True)
    # product = models.ForeignKey(Product, on_delete=DO_NOTHING)

    def __str__(self) -> str:
        return self.title



class Property(models.Model):
    cat = models.ForeignKey(CategoryProduct, related_name='cats', on_delete=models.CASCADE, null=True)
    prop = models.CharField(max_length=255, verbose_name='properties')


    def __str__(self) -> str:
        return self.prop



# class PrimaryProduct(models.Model):
#     title = models.CharField(max_length=255, null=True)
#     cat = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE, null=True)



class Product(models.Model):
    title = models.CharField(max_length=255, null=True)
    description = models.TextField()
    img1 = models.ImageField(upload_to='product_media/', null=True, blank=True)
    img2= models.ImageField(upload_to='product_media/', null=True, blank=True)
    img3 = models.ImageField(upload_to='product_media/', null=True, blank=True)
    img4 = models.ImageField(upload_to='product_media/', null=True, blank=True)
    active = models.BooleanField(default=True)
    date_prodcut = models.DateTimeField(auto_now=True)
    cat = models.ForeignKey(CategoryProduct, related_name='category', on_delete=models.CASCADE, null=True)
    sold_out_num = models.BigIntegerField(blank=True,default=0)
    slug_title=models.SlugField(blank=True,allow_unicode=True)

    def save(self,*args,**kwargs):
        # if not self.slug_title:
        self.slug_title=slugify(self.title,allow_unicode=True)
        super().save(*args,**kwargs)


    def __str__(self) -> str:
        return self.title








    # img = models.ImageField(upload_to='product_media/', null=True, blank=True)

product/views.py
from django.shortcuts import render,redirect
from django.views.generic.detail import DetailView
from .models import CategoryProduct, Product
from django.views.generic import ListView
from django.db.models import Q
from django.core.cache import cache
from supply.models import SalesmanProduct
from comment.forms import CommentForm
from comment.models import Comment
from django.http import JsonResponse
from django.urls import reverse
import redis
import json




def show_sub_cat(request): # --> showing sub_cat after click 
    sub = []
    parent_category = CategoryProduct.objects.all().filter(parent=None)

    for cat in parent_category:
        sub.append(cat.child_cat.all())

    ctx = {
        'sub_category': sub
    }

    return render(request, 'product/sub_cat.html', ctx)


def show_sub_cat_det(request, cat): # --> showing sub_cat after click 
    sub = CategoryProduct.objects.filter(parent__title=cat)

    ctx = {
        'sub_category': sub
    }

    return render(request, 'product/sub_cat.html', ctx)



# class ShowProductBySubCategory(ListView):
#     template_name = 'product/detail_sub_cat.html'
#     context_object_name ='products'
#     paginate_by = 16


#     def get(self, request, *args, **kwargs):
#         self.queryset = Product.objects.all().filter(cat__title=kwargs.get('sub_cat'))
#         return super().get(self, request, *args, **kwargs)



class Detail_Product(DetailView):
    model=Product
    context_object_name_="product"
    template_name ="product/detaile_product.html"
    slug_field = 'slug_title'
    slug_url_kwarg = 'slug'
    # pk_url_kwarg = 'pk'
    
    def get_context_data(self, **kwargs):
         ctx=super().get_context_data(**kwargs)
         first=self.get_object().products.first()
         ctx["first"]=first
         print('first:',first)
         if first:
            l=first.salesproducts.all()
            if l:
                ctx["l"]=l
            sayer=self.get_object().products.all().exclude(salesman=first.salesman)
            ctx["sayer"]=sayer
        
         ctx["form"] =CommentForm()
         ctx["comments"] = self.get_object().product_comment.all()
         category=self.get_object().cat
         same_cat=Product.objects.filter(cat=category).exclude(id=self.get_object().id)
         ctx["same_cat"]=same_cat
         

         return ctx



# class ShowProductCategory(ListView):
#     template_name = 'product/list_product_cat.html'
#     context_object_name ='products'
#     paginate_by = 16

#     def get(self, request, *args, **kwargs):
#         self.queryset = Product.objects.all().filter(cat__parent=kwargs.get('id'))
#         return super().get(self, request, *args, **kwargs)



class FilteringAll(ListView):
    model = SalesmanProduct
    template_name = 'product/side_bar_filtering.html'
    context_object_name = "productlist"
    paginate_by = 8

    def get_queryset(self):
        queryst =  super().get_queryset()
        filter_by_price_1 = self.request.GET.get("price1")
        filter_by_price_2 = self.request.GET.get("price2")
        if filter_by_price_1 is None and filter_by_price_2  is None:
            cache.set("filtering_price", [])
        else:
            cache.set("filtering_price", [filter_by_price_1, filter_by_price_2])
            queryst = SalesmanProduct.objects.filter(Q(price__gte=float(filter_by_price_2)) & Q(price__lte=float(filter_by_price_1)))
            cache.set('filtering_price', queryst)
        return queryst

    # def get_queryset(self):
    #     queryst =  super().get_queryset()

    #     return queryst

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        top_cat = CategoryProduct.objects.filter(parent__isnull=True)
        top_cat_2 = CategoryProduct.objects.filter(parent__isnull=False)
        context["category"] = top_cat
        context["sub_category"] = top_cat_2

        return context
    
    

class ProductList(ListView):
    model = Product
    template_name = 'product/list_products.html'
    context_object_name ='products'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.queryset = Product.objects.filter(cat__title=kwargs.get('category'))
        return super().get(self, request, *args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=None ,**kwargs)
        filtering_by_price = cache.get("filtering_price")
        category = CategoryProduct.objects.filter(parent__isnull=True)
        context["category"] = category
        if filtering_by_price:
            my_dic = {}
            for elm in filtering_by_price:
                my_dic[elm.product.id]=elm.product
            context["my_products"] = my_dic.values

        return context
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(object_list=None ,**kwargs)
    #     category = CategoryProduct.objects.filter(parent__isnull=True)
    #     context["category"] = category

    #     return context
    



def add_to_cart(request, slug: str):
    r=redis.Redis()
    if  request.method=="POST":
        product=request.POST.get("product")
        product_img=request.POST.get("product_img")
        product_number=int(request.POST.get("product_number"))
        unit_price=int(request.POST.get("price"))
        salesman_product_id=int(request.POST.get("salesman_product_id"))
        salesman=request.POST.get("salesman")
        items_list=[product_number,product_img,unit_price,salesman,salesman_product_id]
        items_list=json.dumps(items_list)
        items_dict={product:items_list}
        if request.user.is_authenticated:
            key=request.user.email
            r.hset(key,mapping=items_dict)
            r.expire(key,300)#cart for 300 s remains in cache
        else:
            key=request.session.session_key
            r.hset(key,mapping=items_dict)
            r.expire(key,300)#cart for 300s remains in cache

        return redirect(reverse("products:detail_product",kwargs={"slug":slug}))
        

product/templates/product/detail_sub_cat.html
{% extends 'base.html' %}
{% block content %}
<div class="shop list">
    <!-- Modal view quick -->
    
    <div class="bg-close">
    </div>
    <div class="bg-searchform">
        <div class="area-searchform">
            <div class="area-close-search">
                <a href="#"><i class="fal fa-times"></i></a>
            </div>
            <form class="search-form d-flex w-100" action="" method="get">
                <input type="text" class="form-control input_search" placeholder="دنبال چه میگردید">
                <button type="submit">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z">
                        </path>
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z">
                        </path>
                    </svg>
                </button>
            </form>
        </div>
    </div>
   
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="area-breadcrumb-site">
            <h1 class="text-center mb-3">نمای لیستی فروشگاه</h1>
            <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
                <ol class="breadcrumb breadcrumb-singleProduct ">
                    <li class="breadcrumb-item"><a href="#">خانه</a></li>
                    <li class="breadcrumb-item"><a href="#">فروشگاه</a></li>
                    <li class="breadcrumb-item active">نمای لیستی فروشگاه</li>
                </ol>
            </nav>
        </div>
    </section>
    <div class="tab-content tab-content-shop" id="myTabContent">

        <div class="tab-pane fade show active" id="contentShop3" role="tabpanel"
            aria-labelledby="tab-iconColumnThree">

            <div class="row">
                {% for p in products %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="product_cart">
                        
                           
                            <div class="cart-img-product mb-3">
                                <a href="#">
                                    <div class="d-flex justify-content-center align-items-center h-100">
                                        <img src="{{p.img1.url}}" class="img1-product img-fluid" />
                                    </div>
                                </a>
                            <div class="area-button-view-product">
                                  <a href="#" class="button-view-product">مشاهده محصول </a>
                                
                            </div>
                        </div>
                        <div class="content_product text-center">
                            <a href="#">
                                <h3 class="title-product mb-2">{{p.title}}</h3>
                            </a>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>

        </div>

    </div>
  
    <a class="scrollTo scroll-To-top" href=".topbar-site"></a>
    <script src="js/jquery-3.6.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/wow.min.js"></script>
    <script type="text/javascript" src="js/price-range-slider.js"></script>
    <script src="js/jquery.elevatezoom.js"></script>
</div>
{% endblock %}

product/templates/product/list_product_cat.html
{% comment %} {% extends 'base.html' %}
{% block content %}
<div class="shop list">
    <!-- Modal view quick -->
    
    <div class="bg-close">
    </div>
    <div class="bg-searchform">
        <div class="area-searchform">
            <div class="area-close-search">
                <a href="#"><i class="fal fa-times"></i></a>
            </div>
            <form class="search-form d-flex w-100" action="" method="get">
                <input type="text" class="form-control input_search" placeholder="دنبال چه میگردید">
                <button type="submit">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z">
                        </path>
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z">
                        </path>
                    </svg>
                </button>
            </form>
        </div>
    </div>
   
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="area-breadcrumb-site">
            <h1 class="text-center mb-3">نمای لیستی فروشگاه</h1>
            <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
                <ol class="breadcrumb breadcrumb-singleProduct ">
                    <li class="breadcrumb-item"><a href="#">خانه</a></li>
                    <li class="breadcrumb-item"><a href="#">فروشگاه</a></li>
                    <li class="breadcrumb-item active">نمای لیستی فروشگاه</li>
                </ol>
            </nav>
        </div>
    </section>
    <div class="tab-content tab-content-shop" id="myTabContent">

        <div class="tab-pane fade show active" id="contentShop3" role="tabpanel"
            aria-labelledby="tab-iconColumnThree">

            <div class="row">
                {% for p in products %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="product_cart">
                        
                           
                            <div class="cart-img-product mb-3">
                                <a href="#">
                                    <div class="d-flex justify-content-center align-items-center h-100">
                                        <img src="{{p.img1.url}}" class="img1-product img-fluid" />
                                    </div>
                                </a>
                            <div class="area-button-view-product">
                                  <a href="{% url 'products:detail_product' p.id%}" class="button-view-product">مشاهده محصول </a>
                                
                            </div>
                        </div>
                        <div class="content_product text-center">
                            <a href="#">
                                <h3 class="title-product mb-2">{{p.title}}</h3>
                            </a>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>

        </div>

    </div>
  
    <a class="scrollTo scroll-To-top" href=".topbar-site"></a>
    <script src="js/jquery-3.6.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/wow.min.js"></script>
    <script type="text/javascript" src="js/price-range-slider.js"></script>
    <script src="js/jquery.elevatezoom.js"></script>
</div>
{% endblock %} {% endcomment %}

product/templates/product/list_products.html
{% extends 'base.html' %}
{% load render_partial %}

{% block content %}
<div class="shop list">
    <!-- Modal view quick -->
    
    <div class="bg-close">
    </div>
    <div class="bg-searchform">
        <div class="area-searchform">
            <div class="area-close-search">
                <a href="#"><i class="fal fa-times"></i></a>
            </div>
            <form class="search-form d-flex w-100" action="" method="get">
                <input type="text" class="form-control input_search" placeholder="دنبال چه میگردید">
                <button type="submit">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z">
                        </path>
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z">
                        </path>
                    </svg>
                </button>
            </form>
        </div>
    </div>
   
    <section class="mb-5 pb-sm-2 pb-md-3  pb-lg-4 pb-xl-5">
        <div class="area-breadcrumb-site">
            <h1 class="text-center mb-3">نمای لیستی فروشگاه</h1>
            <nav aria-label="breadcrumb" class="mb-4 mb-lg-3">
                <ol class="breadcrumb breadcrumb-singleProduct ">
                    <li class="breadcrumb-item"><a href="#">خانه</a></li>
                    <li class="breadcrumb-item"><a href="#">فروشگاه</a></li>
                    <li class="breadcrumb-item active">نمای لیستی فروشگاه</li>
                </ol>
            </nav>
        </div>
    </section>
    <main class="content">
        <div class="container">
            <div class="row">
                <div class="tab-content tab-content-shop" id="myTabContent">

                    <div class="tab-pane fade show active" id="contentShop3" role="tabpanel"
                        aria-labelledby="tab-iconColumnThree">
            
                        <div class="row">
                            {% if my_products %}
                                {% for p in my_products %}
                                    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                        <div class="product_cart">
                                                <div class="cart-img-product mb-3">
                                                    <a href="{% url 'product:detail_product' p.id %}">
                                                    {% comment %} <a href="{% url 'products: detail_product' product.id%}"> {% endcomment %}
                                                        <div class="d-flex justify-content-center align-items-center h-100">
                                                            <img src="{{p.img1.url}}" class="img1-product img-fluid" />
                                                        </div>
                                                    </a>
                                                <div class="area-button-view-product">
                                                    <a href="{% url 'product:detail_product' p.id %}" class="button-view-product">مشاهده محصول </a>
                                                    {% comment %} <a href="{% url 'products: detail_product' product.id%}" class="button-view-product">مشاهده محصول </a> {% endcomment %}
                                                    
                                                </div>
                                            </div>
                                            <div class="content_product text-center">
                                                <a href="{% url 'product:detail_product' p.id %}">
                                                {% comment %} <a href="{% url 'products: detail_product' product.id%}"> {% endcomment %}
                                                    <h3 class="title-product mb-2">{{p.title}}</h3>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                {%endfor%}
                            {% else %}
                                {% for p in products %}
                                    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                        <div class="product_cart">
                                        
                                                <div class="cart-img-product mb-3">
                                                    <a href="{% url 'product:detail_product' p.id %}">
                                                        <div class="d-flex justify-content-center align-items-center h-100">
                                                            <img src="{{p.img1.url}}" class="img1-product img-fluid" />
                                                        </div>
                                                    </a>
                                                <div class="area-button-view-product">
                                                    <a href="{% url 'product:detail_product' p.id %}" class="button-view-product">مشاهده محصول </a>
                                                    
                                                </div>
                                            </div>
                                            <div class="content_product text-center">
                                                <a href="{% url 'product:detail_product' p.id %}">
                                                    <h3 class="title-product mb-2">{{p.title}}</h3>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                {%endfor%}

                            {% endif %}

                            
                        </div>
            
                    </div>
                    {% render_partial 'product:side_bar_filtering' %}
                </div>


            </div>
        </div>
    </main>


    <a class="scrollTo scroll-To-top" href=".topbar-site"></a>
    <script src="js/jquery-3.6.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/wow.min.js"></script>
    <script type="text/javascript" src="js/price-range-slider.js"></script>
    <script src="js/jquery.elevatezoom.js"></script>
</div>
{% endblock %}

product/templates/product/side_bar_filtering.html
{% load static %}

<div class="col-12 col-lg-3 mt-5 mt-lg-0 order-2 ">
    <form method="GET">
    <aside class="area-sidebar">
            <div class="widget-sidebar mb-4 pb-3" id="accordian">
                <header>
                    <h3 class="title-widget-sidebar ">دسته بندی</h3>
                </header>
                <section>
                    <ul class="menu-multi-level menu-categorySidebar">
                        {% for cat in category %}
                        <li class="menu-item-has-children"><a href="{% url "product:show_product" cat.id %}">{{ cat.title }}<span class="badge-sidebar-shop">(150)</span></a>
                            <ul class="sub-menu" style="display: none;">
                                {% for sub_cat in sub_category %}
                                {% if sub_cat.parent_id == cat.id %}
                                <li class="children"><a href="{% url "product:show_product" sub_cat %}">{{ sub_cat.title }}<span class="badge-sidebar-shop">(10)</span> </a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </section>
            </div>
            <div class="widget-sidebar mb-4 pb-3">
                <header>
                    <h3 class="title-widget-sidebar">قیمت</h3>
                </header>
                <section>

                    <div class="area-range-price extra-controls form-inline">
                        {% comment %} <div class="form-group w-100  ">
                            <select name="price">
                                <option>قیمت </option>
                                    <option value="500000,990000">500000 تومان - 990000 تومان</option>
                                <option value="1000000,2000000">1000000 تومان - 2000000 تومان</option>
                                <option value="3000000,5000000">3000000 تومان - 5000000 تومان</option>
                                <option value="5000000,9000000">5000000 تومان - 9000000 تومان</option>
                            </select>

                        </div> {% endcomment %}
                        <div class="area-range-price extra-controls form-inline">
                            <div class="form-group w-100  ">
                                <span>محدوده : </span>
                                <input class="js-input-from form-control " value="0" name="price2">
                                تا
                                <input type="text" class="js-input-to form-control  " value="0" name="price1">
                            </div>
                        </div>


                    </div>

                </section>
            </div>
            <input type="submit"/>
        </aside>
    </form>
</div>

product/templates/product/sub_cat.html
{% extends 'base.html' %}
{% block content %}
<div class="shop list">
    <!-- Modal view quick -->
    
    <div class="bg-close">
    </div>
    <div class="bg-searchform">
        <div class="area-searchform">
            <div class="area-close-search">
                <a href="#"><i class="fal fa-times"></i></a>
            </div>
            <form class="search-form d-flex w-100" action="" method="get">
                <input type="text" class="form-control input_search" placeholder="دنبال چه میگردید">
                <button type="submit">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z">
                        </path>
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z">
                        </path>
                    </svg>
                </button>
            </form>
        </div>
    </div>
    
    <div class="tab-content tab-content-shop" id="myTabContent">

        <div class="tab-pane fade show active" id="contentShop3" role="tabpanel"
            aria-labelledby="tab-iconColumnThree">

            <div class="row">
                {% for c in sub_category %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="product_cart">
                        
                           
                            <div class="cart-img-product mb-3">
                                <a href="#">
                                    <div class="d-flex justify-content-center align-items-center h-100">
                                        <img src="{{c.img.url}}" class="img1-product img-fluid" />
                                    </div>
                                </a>
                            <div class="area-button-view-product">
                                  <a href="{% url 'product:show_product' c.title %}" class="button-view-product"> مشاهده محصولات {{c.title}}</a>
                                
                            </div>
                        </div>
                        <div class="content_product text-center">
                            <a href="{% url 'product:show_product' c.title %}">
                                <h3 class="title-product mb-2">{{c.title}}</h3>
                            </a>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>

        </div>

    </div>
  
    <a class="scrollTo scroll-To-top" href=".topbar-site"></a>
    <script src="js/jquery-3.6.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="js/wow.min.js"></script>
    <script type="text/javascript" src="js/price-range-slider.js"></script>
    <script src="js/jquery.elevatezoom.js"></script>
</div>
{% endblock %}